{{- if .Values.rbd_key }}
---
apiVersion: v1
data:
  key: {{ .Values.rbd_key }}
kind: Secret
type: kubernetes.io/rbd
metadata:
  name: {{ .Values.rbd_sc_name }}
  namespace: {{ .Values.namespace }}
{{- end }}
