---
apiVersion: v1
kind: Service
metadata:
  name: loghouse
  namespace: {{ .Values.namespace }}
spec:
  selector:
    component: loghouse
  ports:
  - name: http
    port: 9292
    targetPort: 9292
    protocol: TCP
