---
apiVersion: v1
kind: Service
metadata:
  name: tabix
  namespace: {{ .Values.namespace }}
spec:
  selector:
    component: tabix
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
