apiVersion: v1
entries:
  loghouse:
  - created: 2017-10-31T10:05:10.505937612+03:00
    description: Loghouse (Fluentd, Clickhouse, Tabix, Loghouse) for collect and prepare
      logs for Kubernetes cluster.
    digest: 53fb1ac409492d0a5a7a957f95fa6307b32ff85a48e0d794cabb05d709c6a733
    keywords:
    - fluentd
    - clickhouse
    - tabix
    - loghouse
    - kubernetes
    maintainers:
    - email: dmitry.stolyarov@flant.com
      name: Dmitry Stolyarov
    - email: andrey.sidorov@flant.com
      name: Andrey Sidorov
    - email: sergey.gnuskov@flant.com
      name: Sergey Gnuskov
    name: loghouse
    urls:
    - loghouse-0.0.3.tgz
    version: 0.0.3
generated: 2017-10-31T10:05:10.504815349+03:00
