{{- if not .Values.clickhouse.password -}}
{{- set .Values.clickhouse "password" (randAlphaNum 16) -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: clickhouse
type: Opaque
data:
  CLICKHOUSE_USER: {{ .Values.clickhouse.user | b64enc }}
  CLICKHOUSE_PASSWORD: {{ .Values.clickhouse.password | b64enc }}
